import { uuidv4, isUuidV4 } from '../index';

const UUID_V4_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

describe('uuidv4()', () => {
  it('returns a string', () => {
    expect(typeof uuidv4()).toBe('string');
  });

  it('matches the UUID v4 format', () => {
    expect(uuidv4()).toMatch(UUID_V4_REGEX);
  });

  it('version nibble is always "4"', () => {
    for (let i = 0; i < 100; i++) {
      const id = uuidv4();
      expect(id[14]).toBe('4');
    }
  });

  it('variant nibble is always 8, 9, a, or b', () => {
    const validVariants = new Set(['8', '9', 'a', 'b']);
    for (let i = 0; i < 100; i++) {
      const id = uuidv4();
      expect(validVariants.has(id[19])).toBe(true);
    }
  });

  it('produces unique values', () => {
    const ids = new Set(Array.from({ length: 1000 }, () => uuidv4()));
    expect(ids.size).toBe(1000);
  });

  it('has the correct length (36 characters)', () => {
    expect(uuidv4()).toHaveLength(36);
  });

  it('contains hyphens at positions 8, 13, 18, and 23', () => {
    const id = uuidv4();
    expect(id[8]).toBe('-');
    expect(id[13]).toBe('-');
    expect(id[18]).toBe('-');
    expect(id[23]).toBe('-');
  });
});

describe('isUuidV4()', () => {
  it('returns true for a valid UUID v4 generated by uuidv4()', () => {
    expect(isUuidV4(uuidv4())).toBe(true);
  });

  it('returns true for a known valid UUID v4', () => {
    expect(isUuidV4('a3bb189e-8bf9-4888-9912-ace4e6543002')).toBe(true);
  });

  it('returns true for uppercase UUID v4', () => {
    expect(isUuidV4('A3BB189E-8BF9-4888-9912-ACE4E6543002')).toBe(true);
  });

  it('returns false for an empty string', () => {
    expect(isUuidV4('')).toBe(false);
  });

  it('returns false for a random string', () => {
    expect(isUuidV4('not-a-uuid')).toBe(false);
  });

  it('returns false for a UUID v1 (version nibble is not 4)', () => {
    expect(isUuidV4('110e8400-e29b-11d4-a716-446655440000')).toBe(false);
  });

  it('returns false for a UUID with an invalid variant nibble', () => {
    // variant nibble is 'c' which is not 8, 9, a, or b
    expect(isUuidV4('a3bb189e-8bf9-4888-c912-ace4e6543002')).toBe(false);
  });

  it('returns false for a UUID missing hyphens', () => {
    expect(isUuidV4('a3bb189e8bf9488899124ace4e6543002')).toBe(false);
  });
});
